# Generated by Django 3.2.18 on 2023-04-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balkancottageapp', '0003_comment_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_page', models.CharField(max_length=120)),
            ],
        ),
    ]
