# Generated by Django 3.2.18 on 2023-04-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balkancottageapp', '0004_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='capacity',
            field=models.CharField(choices=[('4', '4 persons'), ('8', '8 persons'), ('10', '10 persons')], max_length=2),
        ),
    ]
