# Generated by Django 3.2.18 on 2023-04-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balkancottageapp', '0005_auto_20230428_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='content',
            field=models.CharField(max_length=999),
        ),
    ]
