# Generated by Django 3.2.18 on 2023-08-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balkancottageapp', '0006_alter_menu_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='content',
            field=models.CharField(max_length=250),
        ),
    ]
