# Generated by Django 3.2.18 on 2023-08-04 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balkancottageapp', '0008_alter_menu_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='extra',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
