# Generated by Django 3.2.18 on 2023-08-11 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balkancottageapp', '0009_auto_20230804_1721'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table',
        ),
    ]
