# Generated by Django 3.2.18 on 2023-08-13 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balkancottageapp', '0010_delete_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='table',
        ),
    ]
