# Generated by Django 3.2.18 on 2023-08-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balkancottageapp', '0012_reservation_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='message',
            field=models.TextField(default='Special requests, alergies etc.', max_length=300),
        ),
    ]
